---
- hosts: webserver
  become: yes
  become_user: root
  tasks:
      - name: Install EPEL release for nginx
        yum: name=epel-release state=present

      - name: Install nginx web server
        yum: name=nginx state=installed update_cache=true
        notify:
          - start nginx

  handlers:
      - name: start nginx
        service: name=nginx enabled=yes state=started

